### ISSUE TITLE
Can't connect via TCP

### ISSUE THREAD

**Issue by Sainan** [Ekopalypse/NppLspClient#10]
I'm trying to use the [Pluto Language Server](https://github.com/PlutoLang/pluto-language-server) with the following configuration:
```INI
[lspservers.lua]
mode = "tpc"
executable = 'C:\Windows\System32\PING.EXE'
args = ''
auto_start_server = false
port = 9170
host = "127.0.0.1"
```
The server is running fine, but the logs seem to indicate that the client attempts to write to an un-opened socket(?)
![image](https://user-images.githubusercontent.com/63328889/233391046-16e3de70-4dc3-475e-ae8f-e7a828ee75a7.png)

I know it's not a broken pipe because the language server would've logged any connection events, and the plugin would've probably thrown "ERROR: attempt to write to non-existent pipe".

**Comment by Ekopalypse** [comment]
Thanks for your interest.
Just tested it with Npp 8.5.2 and the latest version of NppLspClient and it seems to work with tcp when I use python.

![image](https://user-images.githubusercontent.com/47723516/233469430-8c7e09af-ea73-40d4-acdb-ac55fd53299a.png)
Did you restart Npp after configuring the server? Or run "apply current configuration"?
I am not familiar with pluto ls. Can you give me a small script and describe what I need to do to set it up so I can test it?

**Comment by Ekopalypse** [comment]
I was able to start and communicate with the server.

![image](https://user-images.githubusercontent.com/47723516/233476629-5ec71fc1-1c38-4553-88ec-d9c4d3dc9124.png)

**Comment by Ekopalypse** [comment]
Seems the pluto ls is terminating the session

![image](https://user-images.githubusercontent.com/47723516/233481714-19180e7e-5cc5-4680-902f-115e7c89a4da.png)

**Comment by Sainan** [comment]
In my example I explicitly asked the NppLspClient to launch PING.EXE but still connect to localhost at port 9170 so I could monitor the standard output of the Pluto language server for connection events.

Is it possible that this plugin checks if the process is still running? If so, then I guess that's fine and expected behaviour.

**Comment by Sainan** [comment]
Nevermind, I'm just now trying sublimelsp again and I _also_ can't connect via TCP. I guess something broke on my end of things.

**Comment by Ekopalypse** [comment]
I re-downloaded everything today, because I'm running the test within a sandbox, and was able to communicate with the server using cmd.exe (instead of ping.exe) as the fake pluto ls.

![image](https://user-images.githubusercontent.com/47723516/233604616-8725c16e-b7eb-4c77-89e0-f5a3c0e7b6de.png)

but at some point it got disconnected as you see in the screenshot.

BUT there is a problem when using pluto ls directly, but to be honest I don't understand why as it is still tcp from a communication standpoint.

![image](https://user-images.githubusercontent.com/47723516/233607832-4001a749-8aba-4a50-acee-667e5f5d9f26.png)

There is an initial communication, the client sends the initialization request, the server responds and then some other messages are sent by the client until the connection is broken.

**Comment by Sainan** [comment]
Yeah, it seems for you it disconnects after a C++ exception is thrown.

But for me the issue is that I can't get it to connect via TCP at all. Even using CMD.EXE (so the dummy subprocess stays alive), it just fails like so:
![image](https://user-images.githubusercontent.com/63328889/233613284-4d5c672e-eadb-4eed-9f08-ab0ef36484b4.png)

I am using the latest release build (v0.0.13-alpha), maybe you already fixed it since then.

**Comment by Ekopalypse** [comment]
No, I am using the latest public version when testing. Hmm, that's strange.
How do you test, what operating system and npp version?

**Comment by Sainan** [comment]
Notepad++ v8.5.2 on Windows 10

**Comment by Ekopalypse** [comment]
That is the same as I have.

**Comment by Sainan** [comment]
That's strange. Idk, must be _something_ about my machine, then. Not a huge issue since I can use the stdio to tcp proxy and that works fine.

**Comment by Ekopalypse** [comment]
Do you or did you get this usual allow prorgam x to open a port message?
Maybe a firewall issue

**Comment by Sainan** [comment]
Turned off firewall, still same issue. I do use a VPN, tho (Mullvad), and seems the same with Wireguard and OpenVPN protocols.

**Comment by Ekopalypse** [comment]
I'm running out of ideas and on the verge of doing something private. I'll check back later, if you think of anything else you want me to test, feel free to let me know, I'm interested in making it work.

**Comment by Ekopalypse** [comment]
It looks like your problem of having no communication at all is due to the misspelled
tpc vs tcp entry. I can replicate your behavior if I configure it that way as well.

![image](https://user-images.githubusercontent.com/47723516/233668368-e6d86f2a-a603-4a51-859d-10870029b1d6.png)

Reopening, as this MUST be catched by the npplspclient.

**Comment by Ekopalypse** [comment]
from version v.0.0.30 tcp support is available
